# Generated by Django 6.1 on 2026-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default='')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bitácora de Turno',
                'verbose_name_plural': 'Bitácoras de Turno',
            },
        ),
        migrations.CreateModel(
            name='EnlaceDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icono', models.CharField(default='📘', help_text='Ej: 📘, 🔗, ⚙️', max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Enlace de Documentación',
                'verbose_name_plural': 'Enlaces de Documentación',
                'ordering': ['orden'],
            },
        ),
    ]
