# Generated by Django 6.1 on 2026-08-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bitacora_enlacedocumentacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnlaceDocumentacion',
        ),
    ]
