# Generated by Django 6.1 on 2026-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_enlacedocumentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correos', models.TextField(help_text='Correos separados por punto y coma (;) o comas (,)')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.DeleteModel(
            name='ClienteCentro',
        ),
    ]
