name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Deploy app
      run: |
        cd /var/www/portal_soporte
        
        # Descargar los últimos cambios
        git pull origin main
        
        # Activar entorno y actualizar dependencias
        source .venv/bin/activate
        pip install -r requirements.txt
        
        # Ejecutar comandos de Django
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
        
        # Reiniciar el servicio
        sudo systemctl restart portal
